public struct ShellFunctionGenerator {
    public static func generate() -> String {
        """
        # orbital shell integration
        # Generated by: orbital init
        # Add to ~/.zshrc: eval "$(orbital init)"

        orbital() {
          local cmd="${1:-}"
          case "$cmd" in
            use)
              if [ -z "${2:-}" ]; then
                echo "Usage: orbital use <name>" >&2
                return 1
              fi
              # Unexport previous env vars if switching
              if [ -n "${ORBITAL_ACTIVE_ENV:-}" ]; then
                eval "$(command orbital _unexport "$ORBITAL_ACTIVE_ENV" 2>/dev/null || true)"
              fi
              local exports
              exports=$(command orbital _export "$2") || { echo "orbital: environment '$2' not found" >&2; return 1; }
              eval "$exports"
              export ORBITAL_ACTIVE_ENV="$2"
              echo "Switched to environment: $2"
              ;;
            deactivate)
              if [ -n "${ORBITAL_ACTIVE_ENV:-}" ]; then
                eval "$(command orbital _unexport "$ORBITAL_ACTIVE_ENV" 2>/dev/null || true)"
                unset ORBITAL_ACTIVE_ENV
              fi
              unset CLAUDE_CONFIG_DIR CODEX_CONFIG_DIR GEMINI_CONFIG_DIR
              echo "Deactivated orbital environment"
              ;;
            *)
              command orbital "$@"
              ;;
          esac
        }

        _orbital_init() {
          local orbital_home="${ORBITAL_HOME:-$HOME/.orbital}"
          local current_file="$orbital_home/current"
          if [ -f "$current_file" ]; then
            local env_name
            env_name=$(cat "$current_file" 2>/dev/null)
            if [ -n "$env_name" ]; then
              orbital use "$env_name" 2>/dev/null || true
            fi
          fi
        }
        _orbital_init
        """
    }
}
